/**
 * 🔧 CONFIGURATION FILE - GENERATED BY MY BANK
 */

// 1. BACKEND CONNECTION
const SCRIPT_URL = 'PASTE_YOUR_WEB_APP_URL_HERE'; 

// 🔒 SECURITY KEY
const APP_SECRET = null; 

// 2. SETTINGS
const DEFAULT_EXCHANGE_RATES = { "THB": 1, "USD": 32, "MMK": 0.008 };

// 3. CATEGORY CONFIGURATION
const DEFAULT_CATEGORY_CONFIG = {
    "Daily Living": { "type": "EXPENSE", "subs": ["Food", "Transport", "Utilities", "Household", "Family", "Donation", "Parent", "Baby", "IT Equipments and Accessories"] },
            "Lifestyle": { "type": "EXPENSE", "subs": ["Clothes", "Cosmetic", "Entertainment", "Wearable"] },
            "Agriculture": { "type": "EXPENSE", "subs": ["Agri Inputs", "Tools", "Labor"] },
            "Assets & Savings": { "type": "ASSET", "subs": ["Gold", "Stocks", "Land", "Building", "Savings"] },
            "Loans": { "type": "LIABILITY", "subs": ["Loan Received", "Loan Repayment", "Loan Interest"] },
            "Income": { "type": "INCOME", "subs": ["Salary", "Bonus", "Other"] },
            "Vehicle & Licenses": { "type": "EXPENSE", "subs": ["Motorcycle", "Car", "Motorcycle License Renewal", "Car License Renewal", "Driving License Renewal", "Fuel", "Insurance"] },
            "Maintenance": { "type": "EXPENSE", "subs": ["Home", "Appliance Repair", "Car", "Motor Cycle", "Laptop", "Phone", "Other"] },
            "Tech & Electronics": { "type": "EXPENSE", "subs": ["Laptop", "Peripherals", "Software", "Phone", "Tablet", "Other"] },
            "Store Inventory": { "type": "ASSET", "subs": ["Computers", "Peripherals", "Printers & Office", "Networking & Parts"] },
            "Business Sales": { "type": "INCOME", "subs": ["Project Payment", "Consulting Fee", "Product Sale"] }
};

// 4. BUDGETS
const DEFAULT_BUDGET_LIMITS = { 
    "Daily Living": 10000,
            "Lifestyle": 20000,
            "Agriculture": 5000,
            "Assets & Savings": 100000,
            "Store Inventory": 200000, // High limit for business stock
            "Loans": 0,
            "Vehicle & Licenses": 5000,
            "Maintenance": 5000,
            "Tech & Electronics": 15000,
};