/**
 * 🔧 CONFIGURATION FILE - GENERATED BY MY BANK
 */

// 1. BACKEND CONNECTION
const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbyWuhNbu9joyq_Mqo01BKyy6ztobi2YuAFS4dR8xNIzYwUzjGWUrGw7XeqhUnsa3BTE/exec'; 

// 🔒 SECURITY KEY
const APP_SECRET = 'p@ssw0rd'; 

// 2. SETTINGS
const DEFAULT_EXCHANGE_RATES = { "THB": 1, "USD": 32, "MMK": 0.008 };

// 3. CATEGORY CONFIGURATION
const DEFAULT_CATEGORY_CONFIG = {
    "Daily Living": { "type": "EXPENSE", "subs": ["🍔 Food", "🚌 Transport", "⚡ Utilities", "🏠 Household", "👨‍👩‍👧‍👦 Family", "🤲 Donation", "👴 Parent", "👶 Baby", "💻 IT Equipments"] },
    "Lifestyle": { "type": "EXPENSE", "subs": ["👕 Clothes", "💄 Cosmetic", "🍿 Entertainment", "⌚ Wearable"] },
    "Agriculture": { "type": "EXPENSE", "subs": ["🌱 Agri Inputs", "🛠️ Tools", "🧑‍🌾 Labor"] },
    "Assets & Savings": { "type": "ASSET", "subs": ["🥇 Gold", "📈 Stocks", "🏞️ Land", "🏢 Building", "💰 Savings"] },
    "Loans": { "type": "LIABILITY", "subs": ["📥 Loan Received", "💸 Loan Repayment", "📉 Loan Interest"] },
    "Income": { "type": "INCOME", "subs": ["💼 Salary", "🎁 Bonus", "💵 Other"] },
    "Vehicle & Licenses": { "type": "EXPENSE", "subs": ["🏍️ Motorcycle", "🚗 Car", "🪪 Moto License", "🪪 Car License", "🪪 Driving License", "⛽ Fuel", "🛡️ Insurance"] },
    "Maintenance": { "type": "EXPENSE", "subs": ["🏡 Home", "🔧 Appliance Repair", "🚗 Car", "🏍️ Motor Cycle", "💻 Laptop", "📱 Phone", "🛠️ Other"] },
    "Tech & Electronics": { "type": "EXPENSE", "subs": ["💻 Laptop", "🖱️ Peripherals", "💿 Software", "📱 Phone", "📱 Tablet", "🔌 Other"] },
    "Store Inventory": { "type": "ASSET", "subs": ["🖥️ Computers", "🖲️ Peripherals", "🖨️ Printers & Office", "🔌 Networking & Parts"] },
    "Business Sales": { "type": "INCOME", "subs": ["📂 Project Payment", "🗣️ Consulting Fee", "🏷️ Product Sale"] }
};

// 4. BUDGETS
const DEFAULT_BUDGET_LIMITS = { 
    "Daily Living": 10000,
            "Lifestyle": 20000,
            "Agriculture": 5000,
            "Assets & Savings": 100000,
            "Store Inventory": 200000, // High limit for business stock
            "Loans": 0,
            "Vehicle & Licenses": 5000,
            "Maintenance": 5000,
            "Tech & Electronics": 15000,
};